GET /subscriptions/00f9e387-4d2a-4d2d-8113-785d5827878f/providers/Microsoft.Web/locations/westus/managedApis?api-version=2016-06-01

###
###
### Get consrnt links for office365
POST https://management.azure.com/subscriptions/00f9e387-4d2a-4d2d-8113-785d5827878f/resourceGroups/mcp-connectors/providers/Microsoft.Web/connections/office365/listConsentLinks?api-version=2018-07-01-preview
Authorization: Bearer eyJ0eXAiOiJKV1Q
Content-Type: application/json

{
    "parameters": [
        {
            "objectId": "c9e3cc5d-a6a7-43f7-8686-edefa493590e",
            "parameterName": "token",
            "redirectUrl": "http://localhost:8080",
            "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47"
        }
    ]
}


###
### list connections 
GET /subscriptions/00f9e387-4d2a-4d2d-8113-785d5827878f/resourceGroups/mcp-connectors/providers/Microsoft.Web/connections/?api-version=2016-06-01

### get OpenAPI Schema for office365
GET /subscriptions/00f9e387-4d2a-4d2d-8113-785d5827878f/providers/Microsoft.Web/locations/westus/managedApis/office365?api-version=2016-06-01&export=true

